### ISSUE TITLE
1.14.4 - Hammer Ignores Mining Level (2 ways)

### ISSUE THREAD

**Issue by RepoDraghon** [ldtteam/vanilla-tools#12] opened 2019-11-17 09:43 UTC
1st. Ignores mining level if mining like a stone level tool on a stone next to ore of a diamond level.
2nd. I've noticed that the Iron Hammer ignores Redstone that should easily be mined by an Iron Axe.
I am unsure about Diamond Hammers at this point but will update...

**Comment by ravenbuilder934** [comment] 2021-02-05 18:33
Does this still happen on 1.16?

**Comment by ravenbuilder934** [comment] 2021-02-06 16:49
1 is a duplicate of #11 
I can't reproduce 2, my iron hammer mined redstone ore and redstone blocks perfectly fine

**Closed as completed by ravenbuilder934** 2021-02-06 16:49 UTC
Labels: bug, duplicate
